version: "2"
services:
  kafka:
    container_name: kafka_p1
    image: sllopez/kafka_p1
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS:
        "INTERNAL://kafka:9090,\
         EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS:
        "INTERNAL://kafka:9090,\
         EXTERNAL://dockervm:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
        "INTERNAL:PLAINTEXT,\
         EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./practica_big_data_2019:/practica_big_data_2019  
  spark:
    container_name: spark_p1
    image: sllopez/spark_p1
    volumes:
      - ./practica_big_data_2019:/practica
  server:
    container_name: server_p1
    image: sllopez/server_p1
    ports:
      - "5000:5000"
  